# TTS provider configuration
# active_provider can be "elevenlabs" or "speechify"
active_provider: elevenlabs

providers:
  elevenlabs:
    voice_id: "AZnzlk1XvdvUeBnXmlld" # Domi
    model: "eleven_multilingual_v2"
    voice_settings:
      stability: 0.4
      similarity_boost: 0.8
  speechify:
    voice: "cliff"
    language: "en-US"
    model: "simba-english"
    output_dir: "./"
    prefix: "tts_audio"
